sitename: Product Pencil
title: Documentation
email: productpencil@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation source for Product Pencil LLC 
brand: pp-logo.svg
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

timezone: America/New_York

author:
  name: Juan David Figueroa
  email: "productpencil@gmail.com"

# repositiory: https://productpencil.github.io/
twitter_username: productpencil
github_username:  productpencil

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# sass:
#   sass_dir: _sass

google_analytics: UA-NNNNNNNN-N

minima:
  social_links:
    twitter: productpencil
    # github: jekyll
    # stackoverflow: "11111"
    # dribbble: jekyll
    # facebook: jekyll
    # flickr: jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # telegram: jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # mastodon:
    #  - username: jekyll
    #    instance: example.com
    #  - username: jekyll2
    #    instance: example.com

    # gitlab:
    #  - username: jekyll
    #    instance: example.com
    #  - username: jekyll2
    #    instance: example.com

    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon

copyright: Product Pencil LLC

collections_dir: collections
collections: 
  access:
  anger:
  balance:
  care: 
  circumstance:
  civility: 
  clarity:
  comfort:
  competition:
  courage: 
  creativity:
  culture:
  determination:
  ego:
  empathy: 
  equality:
  excuses:
  experience:
  expression:
  feminism:
  fear:
  flexibility: 
  freedom:
  focus:
  grace:
  hope:
  honesty:
  humility:
  interconnected:
  judgement:
  justice: 
  leadership:
  lifestyle:
  limitation:
  love:
  morals:
  necessity:
  open-mindedness:
  optimism:
  oppression:
  perspective:
  pleasure:
  privilege :
  purpose:
  rationality:
  reevaluate:
  refuge:
  risk:
  self-control:
  self-sabatoge:
  selfless:
  social-constructs:
  success:
  time:
  tolerance:
  value:
  wealth:
  wisdom:

# include:

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
